/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIKepalaAdministrasi;
import Model.FilterDashboard;
import Model.RingkasanKPI;
import Model.TotalWilayah;
import Service.KepalaDashboardService;
import UITampilanUtama.BerandaUtama;
import Model.UserAccount;
import UITampilanUtama.BerandaUtama;


/**
 *
 * @author Zyrus
 */
public class BerandaKepala extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger 
            = java.util.logging.Logger.getLogger(BerandaKepala.class.getName());
    private final KepalaDashboardService dashService = new KepalaDashboardService();
    private javax.swing.JScrollPane mainScroll;
    private BarChartPanel top5Chart;
    private UserAccount currentUser;



    /**
     * Creates new form KepalaAdministrasi
     */
    public BerandaKepala() {
        initComponents();
         
        // Bungkus area kanan (jPanel8) dengan scroll
        mainScroll = new javax.swing.JScrollPane(jPanel8);
        mainScroll.setBorder(null);
        mainScroll.getVerticalScrollBar().setUnitIncrement(16);

        // Ganti layout root supaya kiri (jPanel4) tetap fixed, kanan scrollable
        getContentPane().removeAll();
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel4, java.awt.BorderLayout.WEST);
        getContentPane().add(mainScroll, java.awt.BorderLayout.CENTER);

        // Rapikan ukuran
        pack();
        setMinimumSize(new java.awt.Dimension(1100, 700));
        
        // === Ganti panel Top-5 menjadi bar chart ===
        top5Chart = new BarChartPanel();

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.removeAll();
        jPanel5.add(top5Chart, java.awt.BorderLayout.CENTER); // <— TAMBAHKAN INI
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 280));
        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200,200,200)),
            javax.swing.BorderFactory.createEmptyBorder(8,8,8,8)
        ));
        jPanel5.revalidate();
        jPanel5.repaint();

        // atur default combobox & refresh
        KFilterWilayah.setSelectedIndex(0); // Lihat Semua
        KFilterBulan.setSelectedIndex(0);   // Lihat Semua (bukan bulan berjalan)

        // Refresh saat filter berubah
        KFilterWilayah.addActionListener(e -> refreshDashboard());
        KFilterBulan.addActionListener(e -> refreshDashboard());

        // Muat pertama kali
        
        refreshDashboard();
        setLocationRelativeTo(null);
   
    }
    
    public BerandaKepala(UserAccount user) {
        this();                // panggil konstruktor default -> initComponents() sudah jalan
        this.currentUser = user;

        // contoh personalisasi UI
        if (user != null) {
            // misal tampilkan nama di subjudul
            jLabel2.setText(user.getNama() + " (Kepala Administrasi)");
            // atau kalau yang tersedia hanya email:
            // jLabel2.setText(user.getEmail() + " (Kepala Administrasi)");
        }
    }
    
    private void refreshTop5(FilterDashboard filter){
        try {
            java.util.List<TotalWilayah> top = dashService.loadTop5(filter);
            // kalau service mengembalikan lebih dari 5, potong saja:
            if (top != null && top.size() > 5) top = top.subList(0,5);

            if (top == null || top.isEmpty()){
                top5Chart.setData(java.util.Collections.emptyList());
            } else {
                top5Chart.setData(top);
            }
        } catch (Exception ex){
            ex.printStackTrace();
            top5Chart.setData(java.util.Collections.emptyList());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BKepala = new javax.swing.JButton();
        BDashboard = new javax.swing.JButton();
        Penjualan = new javax.swing.JButton();
        BKeluar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        KFilterWilayah = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        KFilterBulan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(19, 52, 30));

        jPanel1.setBackground(new java.awt.Color(19, 66, 34));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REVIVE");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kepala Administrasi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        BKepala.setBackground(new java.awt.Color(19, 65, 30));
        BKepala.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        BKepala.setForeground(new java.awt.Color(255, 255, 255));
        BKepala.setText("Beranda");
        BKepala.setBorder(null);
        BKepala.setBorderPainted(false);
        BKepala.setContentAreaFilled(false);
        BKepala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKepalaActionPerformed(evt);
            }
        });

        BDashboard.setBackground(new java.awt.Color(19, 65, 30));
        BDashboard.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        BDashboard.setForeground(new java.awt.Color(255, 255, 255));
        BDashboard.setText("Dashboard");
        BDashboard.setBorder(null);
        BDashboard.setBorderPainted(false);
        BDashboard.setContentAreaFilled(false);
        BDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDashboardActionPerformed(evt);
            }
        });

        Penjualan.setBackground(new java.awt.Color(19, 65, 30));
        Penjualan.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Penjualan.setForeground(new java.awt.Color(255, 255, 255));
        Penjualan.setText("Penjualan");
        Penjualan.setBorder(null);
        Penjualan.setBorderPainted(false);
        Penjualan.setContentAreaFilled(false);
        Penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenjualanActionPerformed(evt);
            }
        });

        BKeluar.setBackground(new java.awt.Color(19, 65, 30));
        BKeluar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        BKeluar.setForeground(new java.awt.Color(255, 255, 255));
        BKeluar.setText("Keluar");
        BKeluar.setBorder(null);
        BKeluar.setBorderPainted(false);
        BKeluar.setContentAreaFilled(false);
        BKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BKepala, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(BKepala)
                .addGap(30, 30, 30)
                .addComponent(BDashboard)
                .addGap(29, 29, 29)
                .addComponent(Penjualan)
                .addGap(33, 33, 33)
                .addComponent(BKeluar)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 84, 0));
        jPanel9.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rata-Rata Food Waste");

        jLabel12.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hasil");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(204, 81, 0));
        jPanel10.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Wilayah Food Waste Tertinggi");

        jLabel13.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Hasil");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(0, 66, 0));
        jPanel11.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Analisis Wilayah");

        jLabel14.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Hasil");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        jPanel12.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel6.setText("Top 5 Wilayah Dengan Food Waste Tertinggi");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel7.setText("Food Waste diukur dalam kg per bulan");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("FILTER");

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Beranda");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel10.setText("Wilayah");

        KFilterWilayah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lihat Semua", "Samarinda", "Balikpapan", "Kutai Kartanegara", "Bontang", "Sangatta", "Berau", "Kutai Barat", "Kutai Timur", "Penajam Paser Utara", "Mahakam Ulu" }));
        KFilterWilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KFilterWilayahActionPerformed(evt);
            }
        });

        jLabel11.setText("Bulan");

        KFilterBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lihat Semua", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        KFilterBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KFilterBulanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KFilterWilayah, 0, 146, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(KFilterBulan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KFilterWilayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KFilterBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BKepalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKepalaActionPerformed
        this.toFront();
        this.requestFocus();
    }//GEN-LAST:event_BKepalaActionPerformed

    private void BDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDashboardActionPerformed
        if (currentUser != null) {
            new DashboardKepala(currentUser).setVisible(true);
        } else {
            new DashboardKepala().setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_BDashboardActionPerformed

    private void BKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKeluarActionPerformed
        new BerandaUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_BKeluarActionPerformed

    private void KFilterWilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KFilterWilayahActionPerformed
        refreshDashboard();
    }//GEN-LAST:event_KFilterWilayahActionPerformed

    private void KFilterBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KFilterBulanActionPerformed
        refreshDashboard();
    }//GEN-LAST:event_KFilterBulanActionPerformed

    private void PenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenjualanActionPerformed
    // Panggil constructor baru sambil mengirim user yang sedang login
    new PenjualanKepala(this.currentUser).setVisible(true);
    
    // Tutup jendela Beranda
    dispose();
    }//GEN-LAST:event_PenjualanActionPerformed

    
    private void refreshDashboard() {
        java.awt.Cursor old = getCursor();
        setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
        try {
            final int tahun = 2025;

            int idxBulan = KFilterBulan.getSelectedIndex();
            int bulan = (idxBulan <= 0) ? 0 : idxBulan;

            String wilayah = String.valueOf(KFilterWilayah.getSelectedItem());
            if ("Lihat Semua".equalsIgnoreCase(wilayah)) wilayah = null;

            FilterDashboard filter = new FilterDashboard(tahun, bulan, wilayah);
            RingkasanKPI kpi = dashService.loadKpi(filter);

            if (kpi == null) {
                jLabel12.setText("Tidak ada data");
                jLabel13.setText("Tidak ada data");
                jLabel14.setText("0");
            } else {
                String fmtRata       = KepalaDashboardService.fmtKg(kpi.getRataRataKg());
                String fmtTertinggi  = KepalaDashboardService.fmtKg(kpi.getWilayahTertinggiKg());
                jLabel12.setText(fmtRata);
                jLabel13.setText(kpi.getWilayahTertinggi() + " (" + fmtTertinggi + ")");
                jLabel14.setText(String.valueOf(kpi.getTotalAnalisisWilayah()));
            }

            refreshTop5(filter);
        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Gagal memuat beranda: " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            jLabel12.setText("-");
            jLabel13.setText("-");
            jLabel14.setText("0");
            top5Chart.setData(java.util.Collections.emptyList());
        } finally {
            setCursor(old);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BerandaKepala().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDashboard;
    private javax.swing.JButton BKeluar;
    private javax.swing.JButton BKepala;
    private javax.swing.JComboBox<String> KFilterBulan;
    private javax.swing.JComboBox<String> KFilterWilayah;
    private javax.swing.JButton Penjualan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
    // Bar chart minimalis tanpa library eksternal
    private static class BarChartPanel extends javax.swing.JPanel {
        private java.util.List<Model.TotalWilayah> data = java.util.Collections.emptyList();

        public void setData(java.util.List<Model.TotalWilayah> data){
            this.data = (data == null) ? java.util.Collections.emptyList() : data;
            repaint();
        }

        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

            int w = getWidth(), h = getHeight();
            int padL = 50, padR = 20, padT = 20, padB = 60;
            int plotW = Math.max(1, w - padL - padR);
            int plotH = Math.max(1, h - padT - padB);

            // Background plot
            g2.setColor(new java.awt.Color(245,245,245));
            g2.fillRoundRect(padL, padT, plotW, plotH, 12, 12);

            if (data.isEmpty()){
                g2.setColor(java.awt.Color.DARK_GRAY);
                String msg = "Tidak ada data";
                java.awt.FontMetrics fm = g2.getFontMetrics();
                g2.drawString(msg, padL + (plotW - fm.stringWidth(msg))/2, padT + plotH/2);
                g2.dispose();
                return;
            }

            double max = data.stream().mapToDouble(Model.TotalWilayah::getTotalKg).max().orElse(0.0);
            if (max <= 0) max = 1.0; // hindari pembagian nol

            g2.setColor(new java.awt.Color(220,220,220));
            for (int i=0;i<=4;i++){
                int y = padT + (int) Math.round(plotH * i / 4.0);
                g2.drawLine(padL, y, padL + plotW, y);
            }

            int n = data.size();
            int gap = 12; // jarak antar bar
            int barW = Math.max(10, (plotW - gap*(n+1)) / Math.max(1,n));

            // axis Y label sederhana (max)
            g2.setColor(java.awt.Color.GRAY);
            String yMax = String.format("%,.0f kg", max);
            g2.drawString(yMax, padL + 6, padT + 14);

            // bars
            int x = padL + gap;
            java.awt.FontMetrics fm = g2.getFontMetrics();
            for (Model.TotalWilayah row : data){
                double val = row.getTotalKg();
                int barH = (int)Math.round( (val / max) * plotH );
                int y = padT + plotH - barH;

                // batang
                g2.setColor(new java.awt.Color(0, 120, 60)); // hijau lembut (boleh ubah)
                g2.fillRoundRect(x, y, barW, barH, 8, 8);

                // nilai di atas bar
                String labelVal = String.format("%,.0f", val);
                g2.setColor(java.awt.Color.BLACK);
                int txtW = fm.stringWidth(labelVal);
                g2.drawString(labelVal, x + (barW - txtW)/2, y - 4);

                // label wilayah (diputar 45° supaya muat)
                String wilayah = row.getWilayah();
                g2.setColor(java.awt.Color.DARK_GRAY);
                java.awt.geom.AffineTransform at = g2.getTransform();
                g2.rotate(-Math.toRadians(45), x + barW/2.0, padT + plotH + 10);
                g2.drawString(wilayah, x + barW/2 - fm.stringWidth(wilayah)/2, padT + plotH + 18);
                g2.setTransform(at);

                x += barW + gap;
            }

            g2.dispose();
        }

        @Override public java.awt.Dimension getPreferredSize() {
            return new java.awt.Dimension(600, 260);
        }
    }
}