/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UITampilanUtama;
import UITampilanUtama.Register;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.util.Arrays;
import Model.UserAccount;
import Service.AuthService;
import UITampilanUtama.BerandaUtama;
import UIKepalaAdministrasi.DashboardKepala;
import UIKepalaAdministrasi.BerandaKepala;
//import ui.DashboardPelanggan;
import java.util.Optional;
import javax.swing.JOptionPane;
import UIStaffAdministrasi.BerandaStaff;
/**
 *
 * @author Zyrus
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(Login.class.getName());
    private char defaultEchoChar;
    
    private final AuthService authService = new AuthService();
    private UserAccount currentUser;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        
        defaultEchoChar = LoginPassword.getEchoChar();

        LoginPassword.addActionListener((ActionEvent e) -> performLogin());
        LoginUsername.addActionListener((ActionEvent e) -> LoginPassword.requestFocusInWindow());
        
        RegisterLogin.addActionListener(e -> onRegisterClick());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LoginPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        Masuk = new javax.swing.JButton();
        LihatPassword = new javax.swing.JCheckBox();
        RegisterLogin = new javax.swing.JButton();
        BatalkanLogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(19, 52, 30));

        jLabel1.setBackground(new java.awt.Color(19, 52, 30));
        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Masuk");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Belum Memiliki Akun?");

        LoginUsername.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Email");

        LoginPassword.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Password");

        Masuk.setBackground(new java.awt.Color(78, 113, 69));
        Masuk.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        Masuk.setForeground(new java.awt.Color(255, 255, 255));
        Masuk.setText("Masuk");
        Masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukActionPerformed(evt);
            }
        });

        LihatPassword.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        LihatPassword.setForeground(new java.awt.Color(204, 204, 204));
        LihatPassword.setText("Lihat Password");
        LihatPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LihatPasswordActionPerformed(evt);
            }
        });

        RegisterLogin.setBackground(new java.awt.Color(19, 52, 30));
        RegisterLogin.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        RegisterLogin.setForeground(new java.awt.Color(255, 255, 255));
        RegisterLogin.setText("Buat Sekarang");
        RegisterLogin.setBorder(null);
        RegisterLogin.setContentAreaFilled(false);

        BatalkanLogin.setBackground(new java.awt.Color(19, 52, 30));
        BatalkanLogin.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        BatalkanLogin.setForeground(new java.awt.Color(255, 255, 255));
        BatalkanLogin.setText("Batalkan");
        BatalkanLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 0));
        BatalkanLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalkanLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LihatPassword)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RegisterLogin))
                        .addComponent(jLabel1)
                        .addComponent(LoginUsername)
                        .addComponent(LoginPassword)
                        .addComponent(Masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BatalkanLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RegisterLogin))
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(LihatPassword)
                .addGap(42, 42, 42)
                .addComponent(Masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BatalkanLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BCKG 1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukActionPerformed
        performLogin();
    }//GEN-LAST:event_MasukActionPerformed

    private void onRegisterClick() {
        new Register().setVisible(true);
        dispose();
    }
    
    private void LihatPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LihatPasswordActionPerformed
        if (LihatPassword.isSelected()){
            LoginPassword.setEchoChar((char)0);
        }else{
            LoginPassword.setEchoChar(defaultEchoChar);
        }
    }//GEN-LAST:event_LihatPasswordActionPerformed

    private void BatalkanLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalkanLoginActionPerformed
        new BerandaUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_BatalkanLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalkanLogin;
    private javax.swing.JCheckBox LihatPassword;
    private javax.swing.JPasswordField LoginPassword;
    private javax.swing.JTextField LoginUsername;
    private javax.swing.JButton Masuk;
    private javax.swing.JButton RegisterLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void performLogin() {
        String email = LoginUsername.getText().trim();
            char[] passChars = LoginPassword.getPassword();
            String password = new String(passChars);

            if (email.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Email dan password tidak boleh kosong.",
                        "Login Gagal", JOptionPane.WARNING_MESSAGE);
                Arrays.fill(passChars, '\0');
                return;
            }

            Optional<UserAccount> ou = authService.login(email, password);

            if (ou.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Username/Password tidak sesuai",
                        "Login Gagal", JOptionPane.ERROR_MESSAGE);
                LoginPassword.setText("");
                LoginPassword.requestFocusInWindow();
                Arrays.fill(passChars, '\0');
                return;
            }

            UserAccount u = ou.get();
            String role = u.getRole();

            // Notifikasi sukses + role
            JOptionPane.showMessageDialog(
                this,
                "Login berhasil!\nRole: " + role + "\nNama: " + u.getNama(),
                "Berhasil",
                JOptionPane.INFORMATION_MESSAGE
            );

            // [DIUBAH] Routing sesuai role menggunakan if-else if
            if ("Kepala_administrasi".equalsIgnoreCase(role)) {
                new BerandaKepala(u).setVisible(true);
                dispose();
            } else if ("Staff_administrasi".equalsIgnoreCase(role)) {
                new BerandaStaff (u).setVisible(true);
                dispose();
                JOptionPane.showMessageDialog(this, "Dashboard Staff belum diaktifkan.");
            } else if ("Pelanggan".equalsIgnoreCase(role)) {
                // new DashboardPelanggan(u).setVisible(true); dispose();
                JOptionPane.showMessageDialog(this, "Dashboard Pelanggan belum diaktifkan.");
            } else {
                JOptionPane.showMessageDialog(this, "Role tidak dikenali: " + role);
            }

            Arrays.fill(passChars, '\0');
        }
}