/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIStaffAdministrasi;
import Model.Staf; // [BARU] Import kelas konkret Staf
import Model.UserAccount;
import UIStaffAdministrasi.BerandaStaff; // Pastikan ini benar
import UIStaffAdministrasi.TabelProduksi;
import UIStaffAdministrasi.TabelKonsumsi;
import UIStaffAdministrasi.TabelBahanBaku;
/**
 *
 * @author CHRISTIAN
 */
public class LihatTabel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LihatTabel.class.getName());

    // ==== KONTEKS PENGGUNA ====
    // [DIUBAH] Menggunakan tipe konkret Staf
    private final Staf penggunaSaatIni;

    /**
     * Creates new form Pelanggan_Pilih_Tabel
     */
    public LihatTabel(Staf pengguna) {
        if (pengguna == null) {
            throw new IllegalArgumentException("Akun Pengguna tidak boleh kosong (null).");
        }
        this.penggunaSaatIni = pengguna;
        initComponents();
        setelahInisialisasi();
    }
    
    private void setelahInisialisasi() {
        setLocationRelativeTo(null);
        setTitle("Pilih Tabel Laporan - " + penggunaSaatIni.getNama());
        // jLabel2 harus diisi dengan nama dan role pengguna yang sebenarnya
        jLabel2.setText(penggunaSaatIni.getNama() + " (Staf Administrasi)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ButtonBahanBaku = new javax.swing.JButton();
        ButtonProduksi = new javax.swing.JButton();
        ButtonKonsumsi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonKembali = new javax.swing.JButton();
        ButtonTabel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 217, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 81, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonBahanBaku.setBackground(new java.awt.Color(78, 113, 69));
        ButtonBahanBaku.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        ButtonBahanBaku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ikon Bahan Baku (1).png"))); // NOI18N
        ButtonBahanBaku.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonBahanBaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBahanBakuActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonBahanBaku, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 200, 130));

        ButtonProduksi.setBackground(new java.awt.Color(78, 113, 69));
        ButtonProduksi.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        ButtonProduksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ikon Produksi (1).png"))); // NOI18N
        ButtonProduksi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonProduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProduksiActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 200, 130));

        ButtonKonsumsi.setBackground(new java.awt.Color(78, 113, 69));
        ButtonKonsumsi.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        ButtonKonsumsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ikon Konsumsi.png"))); // NOI18N
        ButtonKonsumsi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonKonsumsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKonsumsiActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonKonsumsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 200, 130));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TABEL KONSUMSI");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 200, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TABEL PRODUKSI");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 200, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TABEL BAHAN BAKU");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 200, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PILIH TABEL");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 730, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 730, 390));

        jPanel4.setBackground(new java.awt.Color(19, 52, 30));

        jPanel5.setBackground(new java.awt.Color(19, 66, 34));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REVIVE");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Staff Administrasi");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        ButtonKembali.setBackground(new java.awt.Color(19, 65, 30));
        ButtonKembali.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        ButtonKembali.setForeground(new java.awt.Color(255, 255, 255));
        ButtonKembali.setText("Kembali");
        ButtonKembali.setBorder(null);
        ButtonKembali.setBorderPainted(false);
        ButtonKembali.setContentAreaFilled(false);
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        ButtonTabel.setBackground(new java.awt.Color(19, 65, 30));
        ButtonTabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        ButtonTabel.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTabel.setText("Lihat Tabel");
        ButtonTabel.setBorder(null);
        ButtonTabel.setBorderPainted(false);
        ButtonTabel.setContentAreaFilled(false);
        ButtonTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(ButtonTabel)
                .addGap(18, 18, 18)
                .addComponent(ButtonKembali)
                .addGap(0, 248, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        new BerandaStaff(this.penggunaSaatIni).setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    private void ButtonTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTabelActionPerformed

    private void ButtonProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProduksiActionPerformed
        new TabelProduksi(this.penggunaSaatIni).setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonProduksiActionPerformed

    private void ButtonKonsumsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKonsumsiActionPerformed
        new TabelKonsumsi(this.penggunaSaatIni).setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonKonsumsiActionPerformed

    private void ButtonBahanBakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBahanBakuActionPerformed
        new TabelBahanBaku(this.penggunaSaatIni).setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonBahanBakuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(LihatTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        // [DIUBAH] Gunakan kelas konkret Staf dan tambahkan idHotel=0
        Model.Staf penggunaTes = new Model.Staf(
            2, 
            "Mahesa Adi", 
            "test@mail.com", 
            "pass", 
            "Balikpapan", // Wilayah
            10 // idHotel (sesuaikan dengan data Staff Anda)
        );
        
        java.awt.EventQueue.invokeLater(() -> new LihatTabel(penggunaTes).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBahanBaku;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonKonsumsi;
    private javax.swing.JButton ButtonProduksi;
    private javax.swing.JButton ButtonTabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}