/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIStaffAdministrasi;
import Model.Staf;
import Model.UserAccount;
import Service.LayananStaf;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author CHRISTIAN
 */
public class TabelBahanBaku extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TabelBahanBaku.class.getName());
    
    // ==== KONTEKS PENGGUNA & SERVICE ====
    private final UserAccount penggunaSaatIni;
    private final LayananStaf layananStaf = new LayananStaf();

    // ==== MODEL TABEL ====
    private DefaultTableModel modelTabel;

    /**
     * Creates new form Staff_TableBahanBaku
     */
    public TabelBahanBaku(UserAccount pengguna) {
        if (pengguna == null) {
            throw new IllegalArgumentException("Akun Pengguna tidak boleh kosong (null).");
        }
        this.penggunaSaatIni = pengguna;
        initComponents();
        setelahInisialisasi();
    }
    
    private void setelahInisialisasi() {
        setLocationRelativeTo(null);
        setTitle("Tabel Bahan Baku - " + penggunaSaatIni.getNama());
        // Asumsi jLabel4 adalah label subjudul, berdasarkan kode initComponents Anda
        jLabel4.setText(penggunaSaatIni.getNama() + " (Staf Administrasi)");

        // Atur JTable
        modelTabel = new DefaultTableModel(
            new Object[][]{},
            new String[]{ // 7 Kolom sesuai desain Anda
                "ID BAHAN BAKU", "NAMA BAHAN BAKU", "JENIS BAHAN BAKU", "JUMLAH (KG)", 
                "TANGGAL KADALUWARSA", "HARI TERSISA", "KATEGORI"
            }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        TabelBahanBaku.setModel(modelTabel);
        TabelBahanBaku.getTableHeader().setReorderingAllowed(false);
        
        // Muat data untuk pertama kali
        muatUlangTabel();
    }
    
    private void muatUlangTabel() {
        try {
            modelTabel.setRowCount(0);

            // Panggil service untuk mengambil data bahan baku
            List<LayananStaf.BarisBahanBakuUntukTabel> daftarBaris = layananStaf.ambilDataBahanBaku();

            // Isi tabel baris per baris
            for (LayananStaf.BarisBahanBakuUntukTabel baris : daftarBaris) {
                modelTabel.addRow(new Object[]{
                    baris.idBahanBaku(),
                    baris.nama(),
                    baris.jenis(),
                    baris.jumlah(),
                    baris.tanggalKadaluwarsa(),
                    baris.hariTersisa(),
                    baris.kategoriKadaluwarsa()
                });
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Gagal memuat data bahan baku", ex);
            JOptionPane.showMessageDialog(this, "Gagal memuat data bahan baku: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelBahanBaku = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BahanBaku = new javax.swing.JButton();
        ButtonKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 217, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 81, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelBahanBaku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID BAHAN BAKU", "NAMA BAHAN BAKU", "JENIS BAHAN BAKU", "JUMLAH BAHAN BAKU (KG)", "TANGGAL KADALUWARSA", "JUMLAH HARI TERSISA", "KATEGORI KADALUWARSA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelBahanBaku);
        if (TabelBahanBaku.getColumnModel().getColumnCount() > 0) {
            TabelBahanBaku.getColumnModel().getColumn(0).setResizable(false);
            TabelBahanBaku.getColumnModel().getColumn(1).setResizable(false);
            TabelBahanBaku.getColumnModel().getColumn(2).setResizable(false);
            TabelBahanBaku.getColumnModel().getColumn(3).setResizable(false);
            TabelBahanBaku.getColumnModel().getColumn(4).setResizable(false);
            TabelBahanBaku.getColumnModel().getColumn(5).setResizable(false);
            TabelBahanBaku.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1120, 390));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TABEL BAHAN BAKU");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1170, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1180, 510));

        jPanel6.setBackground(new java.awt.Color(19, 52, 30));

        jPanel7.setBackground(new java.awt.Color(19, 66, 34));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REVIVE");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kepala Administrasi");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        BahanBaku.setBackground(new java.awt.Color(19, 65, 30));
        BahanBaku.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        BahanBaku.setForeground(new java.awt.Color(255, 255, 255));
        BahanBaku.setText("Tabel Bahan Baku");
        BahanBaku.setBorder(null);
        BahanBaku.setBorderPainted(false);
        BahanBaku.setContentAreaFilled(false);
        BahanBaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BahanBakuActionPerformed(evt);
            }
        });

        ButtonKembali.setBackground(new java.awt.Color(19, 65, 30));
        ButtonKembali.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        ButtonKembali.setForeground(new java.awt.Color(255, 255, 255));
        ButtonKembali.setText("Kembali");
        ButtonKembali.setBorder(null);
        ButtonKembali.setBorderPainted(false);
        ButtonKembali.setContentAreaFilled(false);
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BahanBaku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(BahanBaku)
                .addGap(18, 18, 18)
                .addComponent(ButtonKembali)
                .addGap(0, 232, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1353, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void BahanBakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BahanBakuActionPerformed
        muatUlangTabel();
    }//GEN-LAST:event_BahanBakuActionPerformed

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        new LihatTabel((Staf) this.penggunaSaatIni).setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(LihatTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        // [DIUBAH] Gunakan kelas konkret Staf dan tambahkan idHotel=0
        Model.Staf penggunaTes = new Model.Staf(
            2, 
            "Mahesa Adi", 
            "test@mail.com", 
            "pass", 
            "Balikpapan", // Wilayah
            10 // idHotel (sesuaikan dengan data Staff Anda)
        );
        
        java.awt.EventQueue.invokeLater(() -> new LihatTabel(penggunaTes).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BahanBaku;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JTable TabelBahanBaku;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
