/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIStaffAdministrasi;
import Model.UserAccount;
import Service.LayananStaff;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author CHRISTIAN
 */
public class TabelKonsumsi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TabelKonsumsi.class.getName());
    
    // ==== KONTEKS PENGGUNA & SERVICE ====
    private final UserAccount penggunaSaatIni;
    private final LayananStaff layananStaf = new LayananStaff();

    // ==== MODEL TABEL ====
    private DefaultTableModel modelTabel;

    /**
     * Creates new form Staff_TableKonsumsi
     */
    public TabelKonsumsi(UserAccount pengguna) {
        if (pengguna == null) {
            throw new IllegalArgumentException("Akun Pengguna tidak boleh kosong (null).");
        }
        this.penggunaSaatIni = pengguna;
        initComponents();
        setelahInisialisasi();
    }
    
    private void setelahInisialisasi() {
        setLocationRelativeTo(null);
        setTitle("Tabel Konsumsi - Wilayah " + penggunaSaatIni.getWilayahDikelola());
        jLabel2.setText(penggunaSaatIni.getNama() + " (Staf Administrasi)");

        // Atur JTable
        modelTabel = new DefaultTableModel(
            new Object[][]{},
            new String[]{
                "ID KONSUMSI", "ID PRODUKSI", "KATEGORI", "TOTAL TERMAKAN (KG)", "TANGGAL"
            }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Membuat semua sel tidak bisa diedit
            }
        };
        TabelKonsumsi.setModel(modelTabel);
        TabelKonsumsi.getTableHeader().setReorderingAllowed(false);
        
        // Muat data untuk pertama kali
        muatUlangTabel();
    }
    
    /**
     * Mengambil data dari service dan mengisi tabel.
     */
    private void muatUlangTabel() {
        try {
            modelTabel.setRowCount(0); // Kosongkan tabel

            // Panggil service untuk mengambil data konsumsi berdasarkan ID staf
            List<LayananStaff.BarisKonsumsiUntukTabel> daftarBaris = layananStaf.ambilDataKonsumsiUntukStaf(penggunaSaatIni.getIdUser());

            // Isi tabel baris per baris
            for (LayananStaff.BarisKonsumsiUntukTabel baris : daftarBaris) {
                modelTabel.addRow(new Object[]{
                    baris.idKonsumsi(),
                    baris.idProduksi(),
                    baris.kategori(),
                    baris.totalTermakan(),
                    baris.tanggalKonsumsi()
                });
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Gagal memuat data konsumsi", ex);
            JOptionPane.showMessageDialog(this, "Gagal memuat data konsumsi: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelKonsumsi = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonKembali = new javax.swing.JButton();
        ButtonTabelKonsumsi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 217, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 81, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelKonsumsi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID KONSUMSI", "ID PRODUKSI", "TOTAL TERMAKAN (KG)", "KATEGORI KONSUMSI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelKonsumsi);
        if (TabelKonsumsi.getColumnModel().getColumnCount() > 0) {
            TabelKonsumsi.getColumnModel().getColumn(0).setResizable(false);
            TabelKonsumsi.getColumnModel().getColumn(1).setResizable(false);
            TabelKonsumsi.getColumnModel().getColumn(2).setResizable(false);
            TabelKonsumsi.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 890, 390));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TABEL KONSUMSI");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 940, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 950, 510));

        jPanel4.setBackground(new java.awt.Color(19, 52, 30));

        jPanel5.setBackground(new java.awt.Color(19, 66, 34));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REVIVE");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Staff Administrasi");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        ButtonKembali.setBackground(new java.awt.Color(19, 65, 30));
        ButtonKembali.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        ButtonKembali.setForeground(new java.awt.Color(255, 255, 255));
        ButtonKembali.setText("Kembali");
        ButtonKembali.setBorder(null);
        ButtonKembali.setBorderPainted(false);
        ButtonKembali.setContentAreaFilled(false);
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        ButtonTabelKonsumsi.setBackground(new java.awt.Color(19, 65, 30));
        ButtonTabelKonsumsi.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        ButtonTabelKonsumsi.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTabelKonsumsi.setText("Tabel Konsumsi");
        ButtonTabelKonsumsi.setBorder(null);
        ButtonTabelKonsumsi.setBorderPainted(false);
        ButtonTabelKonsumsi.setContentAreaFilled(false);
        ButtonTabelKonsumsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTabelKonsumsiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonTabelKonsumsi, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(ButtonKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(ButtonTabelKonsumsi)
                .addGap(18, 18, 18)
                .addComponent(ButtonKembali)
                .addGap(0, 232, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        new LihatTabel(this.penggunaSaatIni).setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    private void ButtonTabelKonsumsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTabelKonsumsiActionPerformed
        muatUlangTabel();
    }//GEN-LAST:event_ButtonTabelKonsumsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        UserAccount penggunaTes = new UserAccount(2, "Mahesa Adi", "test@mail.com", "pass", "Staff_administrasi", "Balikpapan");
        
        java.awt.EventQueue.invokeLater(() -> new TabelKonsumsi(penggunaTes).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonTabelKonsumsi;
    private javax.swing.JTable TabelKonsumsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}