/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPelanggan;
import Model.Pelanggan;
import Service.LayananPelanggan;
import UITampilanUtama.BerandaUtama;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author CHRISTIAN
 */
public class PelangganHistoryPembelian extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PelangganHistoryPembelian.class.getName());
    
    private final Pelanggan currentUser;
    private final LayananPelanggan pelangganSrv = new LayananPelanggan();
    private DefaultTableModel modelHistory;
    /**
     * Creates new form Pelanggan_HistoryPembelian
     */
    public PelangganHistoryPembelian(Pelanggan user) {
        if (user == null) {
            JOptionPane.showMessageDialog(null, "Error: Akun Pelanggan tidak valid.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        this.currentUser = user;
        initComponents();
        afterInit();
    }
    
    private void afterInit() {
        setLocationRelativeTo(null);
        setTitle("History Pembelian - " + currentUser.getNama());
        jLabel2.setText(currentUser.getNama()); // Nama Pelanggan
        
        setupTabel();
        muatHistory();
    }
    
    /**
     * Menyiapkan model tabel.
     */
    private void setupTabel() {
        modelHistory = new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID TRANSAKSI", "JENIS PRODUK", "JUMLAH (KG)", "TOTAL HARGA", "TANGGAL TRANSAKSI"
            }
        ) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        HistoryPembelian.setModel(modelHistory);
        HistoryPembelian.getTableHeader().setReorderingAllowed(false);
    }
    
    /**
     * Mengambil data history dari service dan mengisi tabel.
     */
    private void muatHistory() {
        try {
            modelHistory.setRowCount(0);
            
            // Panggil service untuk mengambil histori pembelian berdasarkan ID pelanggan
            List<LayananPelanggan.BarisHistory> history = pelangganSrv.ambilHistoryPembelian(currentUser.getIdUser());
            
            for (LayananPelanggan.BarisHistory baris : history) {
                modelHistory.addRow(new Object[]{
                    baris.idTransaksi(),
                    baris.jenisProduk(),
                    baris.jumlahProduk(),
                    baris.totalHarga(), // Sudah dalam format Rupiah
                    baris.tanggalTransaksi()
                });
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Gagal memuat history pembelian", ex);
            JOptionPane.showMessageDialog(this, "Gagal memuat history: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BerandaPelanggan = new javax.swing.JButton();
        BelanjaPelanggan = new javax.swing.JButton();
        HistoryPelanggan = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        HistoryPembelian = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 217, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 52, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(290, 750));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(19, 66, 34));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REVIVE");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pelanggan");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 110));

        BerandaPelanggan.setBackground(new java.awt.Color(19, 52, 30));
        BerandaPelanggan.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        BerandaPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        BerandaPelanggan.setText("BERANDA");
        BerandaPelanggan.setBorder(null);
        BerandaPelanggan.setBorderPainted(false);
        BerandaPelanggan.setContentAreaFilled(false);
        BerandaPelanggan.setMargin(new java.awt.Insets(7, 14, 3, 14));
        BerandaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BerandaPelangganActionPerformed(evt);
            }
        });
        jPanel2.add(BerandaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 40));

        BelanjaPelanggan.setBackground(new java.awt.Color(19, 52, 30));
        BelanjaPelanggan.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        BelanjaPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        BelanjaPelanggan.setText("BELANJA");
        BelanjaPelanggan.setBorder(null);
        BelanjaPelanggan.setBorderPainted(false);
        BelanjaPelanggan.setContentAreaFilled(false);
        BelanjaPelanggan.setMargin(new java.awt.Insets(7, 14, 3, 14));
        BelanjaPelanggan.setSelected(true);
        BelanjaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BelanjaPelangganActionPerformed(evt);
            }
        });
        jPanel2.add(BelanjaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 40));

        HistoryPelanggan.setBackground(new java.awt.Color(19, 52, 30));
        HistoryPelanggan.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        HistoryPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        HistoryPelanggan.setText("HISTORY BELANJA");
        HistoryPelanggan.setBorder(null);
        HistoryPelanggan.setBorderPainted(false);
        HistoryPelanggan.setContentAreaFilled(false);
        HistoryPelanggan.setMargin(new java.awt.Insets(7, 14, 3, 14));
        HistoryPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryPelangganActionPerformed(evt);
            }
        });
        jPanel2.add(HistoryPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 40));

        Keluar.setBackground(new java.awt.Color(19, 52, 30));
        Keluar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Keluar.setForeground(new java.awt.Color(255, 255, 255));
        Keluar.setText("KELUAR");
        Keluar.setBorder(null);
        Keluar.setBorderPainted(false);
        Keluar.setContentAreaFilled(false);
        Keluar.setMargin(new java.awt.Insets(7, 14, 3, 14));
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jPanel2.add(Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 510));

        jPanel3.setBackground(new java.awt.Color(207, 217, 224));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HistoryPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID TRANSAKSI", "JENIS PRODUK", "JUMLAH PRODUK (KG)", "TANGGAL TRANSAKSI", "TOTAL HARGA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(HistoryPembelian);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 870, 390));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel7.setText("HISTORY PEMBELIAN");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 950, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BerandaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BerandaPelangganActionPerformed
        new PelangganBeranda(this.currentUser).setVisible(true);
        dispose();
    }//GEN-LAST:event_BerandaPelangganActionPerformed

    private void BelanjaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BelanjaPelangganActionPerformed
        new PelangganBelanja(this.currentUser).setVisible(true);
        dispose();
    }//GEN-LAST:event_BelanjaPelangganActionPerformed

    private void HistoryPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryPelangganActionPerformed
        muatHistory();
    }//GEN-LAST:event_HistoryPelangganActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        new BerandaUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(PelangganHistoryPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        // [TESTING] Gunakan objek Pelanggan konkret untuk testing
        Pelanggan testUser = new Pelanggan(
            1, "Eko Wijaya", "ekowijayacool@gmail.com", "ekopintar11", "PT Nusantara Globalindo"
        );
        
        java.awt.EventQueue.invokeLater(() -> new PelangganHistoryPembelian(testUser).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BelanjaPelanggan;
    private javax.swing.JButton BerandaPelanggan;
    private javax.swing.JButton HistoryPelanggan;
    private javax.swing.JTable HistoryPembelian;
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}