/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPelanggan;

/**
 *
 * @author CHRISTIAN
 */
public class PelangganHistoryPembelian extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PelangganHistoryPembelian.class.getName());

    /**
     * Creates new form Pelanggan_HistoryPembelian
     */
    public PelangganHistoryPembelian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Keluar = new javax.swing.JButton();
        Pelanggan_Belanja = new javax.swing.JButton();
        Pelanggan_Beranda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Keluar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel_menu_pelanggan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 217, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 52, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(290, 750));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pelanggan");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 30));

        Keluar.setBackground(new java.awt.Color(78, 113, 68));
        Keluar.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        Keluar.setForeground(new java.awt.Color(255, 255, 255));
        Keluar.setText("KELUAR");
        Keluar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Keluar.setMargin(new java.awt.Insets(7, 14, 3, 14));
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jPanel2.add(Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, 40));

        Pelanggan_Belanja.setBackground(new java.awt.Color(78, 113, 68));
        Pelanggan_Belanja.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        Pelanggan_Belanja.setForeground(new java.awt.Color(255, 255, 255));
        Pelanggan_Belanja.setText("BELANJA");
        Pelanggan_Belanja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pelanggan_Belanja.setMargin(new java.awt.Insets(7, 14, 3, 14));
        Pelanggan_Belanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pelanggan_BelanjaActionPerformed(evt);
            }
        });
        jPanel2.add(Pelanggan_Belanja, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 40));

        Pelanggan_Beranda.setBackground(new java.awt.Color(78, 113, 68));
        Pelanggan_Beranda.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        Pelanggan_Beranda.setForeground(new java.awt.Color(255, 255, 255));
        Pelanggan_Beranda.setText("BERANDA");
        Pelanggan_Beranda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pelanggan_Beranda.setMargin(new java.awt.Insets(7, 14, 3, 14));
        Pelanggan_Beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pelanggan_BerandaActionPerformed(evt);
            }
        });
        jPanel2.add(Pelanggan_Beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REVIVE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 30));

        Keluar1.setBackground(new java.awt.Color(78, 113, 68));
        Keluar1.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        Keluar1.setForeground(new java.awt.Color(255, 255, 255));
        Keluar1.setText("HISTORY BELANJA");
        Keluar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Keluar1.setMargin(new java.awt.Insets(7, 14, 3, 14));
        Keluar1.setSelected(true);
        Keluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keluar1ActionPerformed(evt);
            }
        });
        jPanel2.add(Keluar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 510));

        jPanel3.setBackground(new java.awt.Color(207, 217, 224));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabel_menu_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID TRANSAKSI", "JENIS PRODUK", "JUMLAH PRODUK (KG)", "TANGGAL TRANSAKSI", "TOTAL HARGA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabel_menu_pelanggan);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 870, 390));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel7.setText("History Pembelian");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 950, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeluarActionPerformed

    private void Pelanggan_BelanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pelanggan_BelanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pelanggan_BelanjaActionPerformed

    private void Pelanggan_BerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pelanggan_BerandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pelanggan_BerandaActionPerformed

    private void Keluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keluar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Keluar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PelangganHistoryPembelian().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Keluar1;
    private javax.swing.JButton Pelanggan_Belanja;
    private javax.swing.JButton Pelanggan_Beranda;
    private javax.swing.JTable Tabel_menu_pelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
