/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPelanggan;

/**
 *
 * @author CHRISTIAN
 */
public class PelangganBelanja extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PelangganBelanja.class.getName());

    /**
     * Creates new form Pelanggan_Toko
     */
    public PelangganBelanja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Keluar = new javax.swing.JButton();
        Pelanggan_Belanja = new javax.swing.JButton();
        Pelanggan_Beranda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Keluar2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Pelanggan_Belanja_Jumlah = new javax.swing.JTextField();
        Pelanggan_Belanja_Wilayah = new javax.swing.JComboBox<>();
        Pelanggan_Belanja_Kategori = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Keranjang_Pelanggan = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelJenisProduk_menu_pelanggan = new javax.swing.JTable();
        Pelanggan_Tambah = new javax.swing.JButton();
        Pelanggan_Beli = new javax.swing.JButton();
        PelangganKosongkan = new javax.swing.JButton();
        Keluar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 217, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 52, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(290, 750));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pelanggan");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 30));

        Keluar.setBackground(new java.awt.Color(78, 113, 68));
        Keluar.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        Keluar.setForeground(new java.awt.Color(255, 255, 255));
        Keluar.setText("KELUAR");
        Keluar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Keluar.setMargin(new java.awt.Insets(7, 14, 3, 14));
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jPanel2.add(Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, 40));

        Pelanggan_Belanja.setBackground(new java.awt.Color(78, 113, 68));
        Pelanggan_Belanja.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        Pelanggan_Belanja.setForeground(new java.awt.Color(255, 255, 255));
        Pelanggan_Belanja.setText("BELANJA");
        Pelanggan_Belanja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Pelanggan_Belanja.setMargin(new java.awt.Insets(7, 14, 3, 14));
        Pelanggan_Belanja.setSelected(true);
        Pelanggan_Belanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pelanggan_BelanjaActionPerformed(evt);
            }
        });
        jPanel2.add(Pelanggan_Belanja, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 40));

        Pelanggan_Beranda.setBackground(new java.awt.Color(78, 113, 68));
        Pelanggan_Beranda.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        Pelanggan_Beranda.setForeground(new java.awt.Color(255, 255, 255));
        Pelanggan_Beranda.setText("BERANDA");
        Pelanggan_Beranda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pelanggan_Beranda.setMargin(new java.awt.Insets(7, 14, 3, 14));
        Pelanggan_Beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pelanggan_BerandaActionPerformed(evt);
            }
        });
        jPanel2.add(Pelanggan_Beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REVIVE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 30));

        Keluar2.setBackground(new java.awt.Color(78, 113, 68));
        Keluar2.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        Keluar2.setForeground(new java.awt.Color(255, 255, 255));
        Keluar2.setText("HISTORY BELANJA");
        Keluar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Keluar2.setMargin(new java.awt.Insets(7, 14, 3, 14));
        Keluar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keluar2ActionPerformed(evt);
            }
        });
        jPanel2.add(Keluar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 510));

        jPanel3.setBackground(new java.awt.Color(207, 217, 224));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pelanggan_Belanja_Jumlah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.add(Pelanggan_Belanja_Jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 250, 30));

        Pelanggan_Belanja_Wilayah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lihat Semua", "Balikpapan", "Berau", "Bontang", "Kutai Kartanegara", "Kutai Barat", "Kutai Timur", "Mahakam Ulu", "Penajam Paser Utara", "Samarinda", "Sangatta" }));
        Pelanggan_Belanja_Wilayah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.add(Pelanggan_Belanja_Wilayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, -1));

        Pelanggan_Belanja_Kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lihat Semua", "Fresh", "Kompos" }));
        Pelanggan_Belanja_Kategori.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Pelanggan_Belanja_Kategori.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(Pelanggan_Belanja_Kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 250, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Total :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 170, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Jumlah Produk (Kg)");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Kategori");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, -1));

        Tabel_Keranjang_Pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "WILAYAH", "KATEGORI PRODUK", "JUMLAH PRODUK (KG)", "TANGGAL KADALUARSA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabel_Keranjang_Pelanggan);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 570, 180));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Wilayah");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, -1));

        TabelJenisProduk_menu_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "WILAYAH", "KATEGORI PRODUK", "JUMLAH PRODUK (KG)", "TANGGAL KADALUARSA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelJenisProduk_menu_pelanggan);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 570, 180));

        Pelanggan_Tambah.setBackground(new java.awt.Color(235, 156, 53));
        Pelanggan_Tambah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Pelanggan_Tambah.setText("Tambah");
        Pelanggan_Tambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pelanggan_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pelanggan_TambahActionPerformed(evt);
            }
        });
        jPanel3.add(Pelanggan_Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, 40));

        Pelanggan_Beli.setBackground(new java.awt.Color(235, 156, 53));
        Pelanggan_Beli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Pelanggan_Beli.setText("Beli");
        Pelanggan_Beli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pelanggan_Beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pelanggan_BeliActionPerformed(evt);
            }
        });
        jPanel3.add(Pelanggan_Beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 120, 40));

        PelangganKosongkan.setBackground(new java.awt.Color(235, 156, 53));
        PelangganKosongkan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PelangganKosongkan.setText("Kosongkan");
        PelangganKosongkan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PelangganKosongkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PelangganKosongkanActionPerformed(evt);
            }
        });
        jPanel3.add(PelangganKosongkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 120, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 950, 510));

        Keluar1.setBackground(new java.awt.Color(78, 113, 68));
        Keluar1.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        Keluar1.setForeground(new java.awt.Color(255, 255, 255));
        Keluar1.setText("HISTORY BELANJA");
        Keluar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Keluar1.setMargin(new java.awt.Insets(7, 14, 3, 14));
        Keluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keluar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Keluar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeluarActionPerformed

    private void Pelanggan_BelanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pelanggan_BelanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pelanggan_BelanjaActionPerformed

    private void Pelanggan_BerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pelanggan_BerandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pelanggan_BerandaActionPerformed

    private void Pelanggan_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pelanggan_TambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pelanggan_TambahActionPerformed

    private void PelangganKosongkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PelangganKosongkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PelangganKosongkanActionPerformed

    private void Pelanggan_BeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pelanggan_BeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pelanggan_BeliActionPerformed

    private void Keluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keluar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Keluar1ActionPerformed

    private void Keluar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keluar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Keluar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PelangganBelanja().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Keluar1;
    private javax.swing.JButton Keluar2;
    private javax.swing.JButton PelangganKosongkan;
    private javax.swing.JButton Pelanggan_Belanja;
    private javax.swing.JTextField Pelanggan_Belanja_Jumlah;
    private javax.swing.JComboBox<String> Pelanggan_Belanja_Kategori;
    private javax.swing.JComboBox<String> Pelanggan_Belanja_Wilayah;
    private javax.swing.JButton Pelanggan_Beli;
    private javax.swing.JButton Pelanggan_Beranda;
    private javax.swing.JButton Pelanggan_Tambah;
    private javax.swing.JTable TabelJenisProduk_menu_pelanggan;
    private javax.swing.JTable Tabel_Keranjang_Pelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
